In [1]:
import pandas as pd
import numpy as np

In [2]:
date = pd.read_csv('/content/orders.csv')
time = pd.read_csv('/content/messages.csv')

In [4]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [5]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [7]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

**when we load date and time data into pandas, they get default data type as objects. In order to use the pandas function on them, we have to convert their data type to date and time explicitly.**

# **Working with Dates**

In [8]:
# converting to datetime data type
date['date'] = pd.to_datetime(date['date'])

In [9]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

**1. Extract Year**

In [13]:
date['date_year'] = date['date'].dt.year

date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

**2. Extract month**

In [15]:
date['date_month'] = date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

In [17]:
date['date_month_name'] = date['date'].dt.month_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

**3. Extract days**

In [19]:
date['date_day'] = date['date'].dt.day

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [20]:
# day of week

date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [21]:
# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns = ['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [23]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday' , 'Saturday']), 1,0)

date.drop(columns = ['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

**Extract week of the year**

In [24]:
date['date_week'] = date['date'].dt.week

date.drop(columns = ['product_id','city_id','orders']).head()

<ipython-input-24-01ecd6b8a280>:1: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  date['date_week'] = date['date'].dt.week

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

**Extract Quarter**

In [25]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns = ['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

**Extract Semester**

In [26]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1 , 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

**Extract time elapsed between dates**

In [27]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2023, 7, 15, 12, 27, 6, 38273)

In [29]:
# subtracting date from today
today - date['date']

0     1313 days 12:27:06.038273
1     1795 days 12:27:06.038273
2     1726 days 12:27:06.038273
3     1428 days 12:27:06.038273
4     1651 days 12:27:06.038273
                 ...
995   1741 days 12:27:06.038273
996   1682 days 12:27:06.038273
997   1530 days 12:27:06.038273
998   1595 days 12:27:06.038273
999   1369 days 12:27:06.038273
Name: date, Length: 1000, dtype: timedelta64[ns]

In [30]:
# if we only want the difference in number of days

(today - date['date']).dt.days

0      1313
1      1795
2      1726
3      1428
4      1651
       ...
995    1741
996    1682
997    1530
998    1595
999    1369
Name: date, Length: 1000, dtype: int64

In [31]:
# months passed

np.round((today - date['date']) / np.timedelta64(1,'M'),0)

0      43.0
1      59.0
2      57.0
3      47.0
4      54.0
       ...
995    57.0
996    55.0
997    50.0
998    52.0
999    45.0
Name: date, Length: 1000, dtype: float64

# Extracting from time

In [32]:
time

                   date                                                msg
0   2013-12-15 00:50:00                           ищу на сегодня мужика 37
1   2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2   2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3   2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4   2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                  ...                                                ...
995 2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996 2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997 2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998 2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999 2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [33]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [34]:
# converting to datetime datatype

time['date'] = pd.to_datetime(time['date'])

In [36]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [37]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

In [38]:
time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

**Extract time**

In [39]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [40]:
# find time difference

today - time['date']

0     3499 days 11:37:06.038273
1     3363 days 12:47:06.038273
2     3849 days 12:06:06.038273
3     3151 days 11:56:06.038273
4     3548 days 13:16:06.038273
                 ...
995   4138 days 11:37:06.038273
996   3459 days 13:13:06.038273
997   3924 days 12:50:06.038273
998   4040 days 12:53:06.038273
999   3312 days 13:02:06.038273
Name: date, Length: 1000, dtype: timedelta64[ns]

In [41]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.023554e+08
1      2.906092e+08
2      3.325972e+08
3      2.722894e+08
4      3.065950e+08
           ...
995    3.575650e+08
996    2.989052e+08
997    3.390798e+08
998    3.491024e+08
999    2.862037e+08
Name: date, Length: 1000, dtype: float64

In [42]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      5.039257e+06
1      4.843487e+06
2      5.543286e+06
3      4.538156e+06
4      5.109916e+06
           ...
995    5.959417e+06
996    4.981753e+06
997    5.651330e+06
998    5.818373e+06
999    4.770062e+06
Name: date, Length: 1000, dtype: float64

In [43]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      83987.618344
1      80724.785011
2      92388.101677
3      75635.935011
4      85165.268344
           ...
995    99323.618344
996    83029.218344
997    94188.835011
998    96972.885011
999    79501.035011
Name: date, Length: 1000, dtype: float64